name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # 每天凌晨同步
  workflow_dispatch: # 允许你手动点按钮同步

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          target_sync_branch: main
          upstream_sync_repo: lx00924-lx/ai-lmstudio
          upstream_sync_branch: main
          test_mode: false
